id: I9881687B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-24T18:06:07+00:00'
last_modified: '2022-06-16T04:26:02.420486+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W18135
  title: བསྟན་རྩིས་རེའུ་མིག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    7A14:
      image_group_id: I5671
      title: ''
      total_pages: 410
      order: 1
      base_file: 7A14.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
